### ISSUE TITLE
Update report with current AS-54u group results

### ISSUE THREAD

**Issue by idzm** [brstu/MMIPU-2020#109]

**Comment by as005411** [comment]
#167 Updates status of AS-54f up to current date (only merged pull requests).

**Comment by as005411** [comment]
Forgot i can't merge. Close please after merging @idzm

**Comment by as005411** [comment]
@idzm Should I update it today after you merging 3rd labs?

**Comment by idzm** [comment]
@as005411 - today, but a bit later (after reviewing all PR's).

**Comment by as005411** [comment]
> @as005411 - today, but a bit later (after reviewing all PR's).

Should it be like now or what? I see a lot of PRs without any comment.

**Comment by as005411** [comment]
@idzm #181 is up now with clickable checkmarks

**Comment by as005411** [comment]
@idzm could you also merge #180 because it could bring some troubles :)

**Comment by as005411** [comment]
I think we can close this issue?

**Comment by idzm** [comment]
Yes, but after accepting #182.

**Comment by as005411** [comment]
#182 Is good now i believe. So i think you could merge and close
